name: Release Drafter

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Generate version
        id: version
        env: 
          TZ: "Asia/Tokyo"
        run: |
          export VERSION=$(date "+%Y-%m-%d_%H%M%S")
          echo ::set-output name=version::${VERSION}
          echo "Version set to ${VERSION}"

      - name: Create Draft Release
        id: create_release
        uses: release-drafter/release-drafter@v5
        with:
          tag: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
          version: ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}